spring.datasource.url=jdbc:mysql://bdmunicipalidad.cj46gwku0sws.us-east-2.rds.amazonaws.com:3306/bdmunicipalidad?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=Joel
spring.datasource.password=Root.12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs


